# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fba38167a670ff0e48b0943c019e7a789af8f8237491329105df73835fec77c07d3290714c6dd5982a4b83d4e4d9c3d46a2d57e4ac8e68e05927d6bca9721dbc

test:
  secret_key_base: ae8eba1846971cced96ffb70b35f908fe68e838c9e2011b1a9262bcce7484a40cd21d5804dd5c852f9f96bde6dc678b13bd68da8df08e9d280166811a15acf6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
